version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: inbound
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d inbound"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: ["8000:8000"]
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/metrics"]
      interval: 10s
      timeout: 10s
      retries: 5

  worker:
    build:
      context: ../worker
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: "celery -A tasks worker --loglevel=info"
    healthcheck:
      test: ["CMD-SHELL", "celery -A tasks inspect ping -d celery@%h || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  ingestor:
    build:
      context: ..
      dockerfile: Dockerfile.ingestor
    env_file: ../.env
    depends_on:
      worker:
        condition: service_healthy
    command: "python ingestor.py"

  frontend:
    build:
      context: ../frontend
    env_file: ../.env
    ports: ["5173:5173"]
    depends_on:
      backend:
        condition: service_healthy
    # VITE_API_URL will be read from .env via env_file

volumes:
  db-data:
